const assert = require('node:assert/strict');
const { rebase, importGuest, equal } = require('../progress-merge.js');
const bundle = (progress = {}, mock = null, paperRun = null) => ({ progress, mock, paperRun });
assert(equal({ a: 1, b: { x: 2, y: 3 } }, { b: { y: 3, x: 2 }, a: 1 }), 'Postgres JSONB key ordering must not produce a change');
assert(!equal([1, 2], [2, 1]), 'array order must remain significant');

const base = bundle({ notes: { matrix: 'original', cpu: 'remove me' }, completed: ['rank'], bookmarks: ['rank'], attempts: [{ eventId: 'old', correct: true }] });
const local = bundle({ notes: { matrix: 'new explanation' }, completed: ['rank', 'gaussian'], bookmarks: [], attempts: [{ eventId: 'old', correct: true }, { eventId: 'local', correct: false }] });
const remote = bundle({ notes: { matrix: 'original', cpu: 'remove me', graph: 'other device' }, completed: ['rank', 'graph'], bookmarks: ['rank', 'graph'], attempts: [{ eventId: 'old', correct: true }, { eventId: 'remote', correct: true }] });
const result = rebase(base, local, remote);
assert.deepEqual(result.progress.notes, { matrix: 'new explanation', graph: 'other device' });
assert.deepEqual(new Set(result.progress.completed), new Set(['rank', 'graph', 'gaussian']));
assert.deepEqual(result.progress.bookmarks, ['graph']);
assert.deepEqual(new Set(result.progress.attempts.map(x => x.eventId)), new Set(['old', 'local', 'remote']));
assert.equal(remote.progress.notes.matrix, 'original', 'merge must not mutate the server snapshot');

const moduleBase = bundle({ moduleNotes: { 0: 'original', 1: 'remove me' } });
const moduleLocal = bundle({ moduleNotes: { 0: 'new module explanation', 2: 'local module' } });
const moduleRemote = bundle({ moduleNotes: { 0: 'original', 1: 'remove me', 3: 'other device module' } });
assert.deepEqual(rebase(moduleBase, moduleLocal, moduleRemote).progress.moduleNotes, { 0: 'new module explanation', 2: 'local module', 3: 'other device module' }, 'module edits and deletions must merge by module without dropping another device\'s notes');
assert.deepEqual(rebase(bundle(), bundle({ moduleNotes: { 0: 'local' } }), bundle({ moduleNotes: { 1: 'remote' } })).progress.moduleNotes, { 0: 'local', 1: 'remote' }, 'older progress without module notes must merge new notes from both devices');
assert.equal(importGuest(bundle({ moduleNotes: { 0: 'account' } }), bundle({ moduleNotes: { 0: 'guest conflict', 1: 'guest module' } })).progress.moduleNotes[0], 'account');
assert.equal(importGuest(bundle(), bundle({ moduleNotes: { 1: 'guest module' } })).progress.moduleNotes[1], 'guest module');

const richBase = bundle({ notes: { topic: 'Original', deleted: 'Remove' }, noteFormats: { 'notes:topic': { text: 'Original', html: '<b>Original</b>' }, 'notes:deleted': { text: 'Remove', html: '<i>Remove</i>' } } });
const richLocal = bundle({ notes: { topic: 'Original' }, noteFormats: { 'notes:topic': { text: 'Original', html: '<i>Original</i>' } } });
const richRemote = bundle({ notes: { topic: 'Remote text', other: 'Other' }, noteFormats: { 'notes:topic': { text: 'Remote text', html: '<h2>Remote text</h2>' }, 'notes:other': { text: 'Other', html: '<b>Other</b>' } } });
const richMerged = rebase(richBase, richLocal, richRemote).progress;
assert.equal(richMerged.notes.topic, 'Original', 'a formatting-only edit is an edit of the same note');
assert.deepEqual(richMerged.noteFormats['notes:topic'], richLocal.progress.noteFormats['notes:topic'], 'text and HTML must resolve the same-note conflict together');
assert.equal(richMerged.notes.other, 'Other');
assert.equal(richMerged.noteFormats['notes:other'].html, '<b>Other</b>', 'another device\'s separate note retains formatting');
assert.equal(richMerged.noteFormats['notes:deleted'], undefined, 'clearing a rich note deletes its formatting');
const legacyEdit = rebase(richBase, bundle({ notes: { topic: 'Older editor changed the text', deleted: 'Remove' } }), richRemote).progress;
assert.equal(legacyEdit.notes.topic, 'Older editor changed the text');
assert.equal(legacyEdit.noteFormats['notes:topic'], undefined, 'a plain-text update must clear incompatible rich formatting');
assert.deepEqual(rebase(richBase, richBase, richRemote).progress.noteFormats, richRemote.progress.noteFormats, 'unchanged rich notes adopt cloud formatting');
assert.deepEqual(importGuest(bundle(), richBase).progress.noteFormats, richBase.progress.noteFormats, 'guest imports retain rich text');
assert.equal(importGuest(bundle({ notes: { topic: 'Original' } }), richBase).progress.noteFormats['notes:topic'], undefined, 'guest formatting must not replace an existing account plain note on conflict');
assert.deepEqual(importGuest(richLocal, richRemote).progress.noteFormats['notes:topic'], richLocal.progress.noteFormats['notes:topic'], 'import conflicts retain the account text and its matching format together');

const sticky = (content, title = 'Formula') => ({ scope: 'module', moduleId: 0, title, content, color: 'yellow' });
const stickyBase = bundle({ stickyNotes: { edited: sticky('<b>Original</b>'), deleted: sticky('Remove') } });
const stickyLocal = bundle({ stickyNotes: { edited: sticky('<b>Updated</b>'), local: sticky('<ul><li>Local</li></ul>') } });
const stickyRemote = bundle({ stickyNotes: { ...stickyBase.progress.stickyNotes, remote: sticky('<h2>Remote</h2>') } });
assert.deepEqual(rebase(stickyBase, stickyLocal, stickyRemote).progress.stickyNotes, { edited: sticky('<b>Updated</b>'), local: sticky('<ul><li>Local</li></ul>'), remote: sticky('<h2>Remote</h2>') }, 'different sticky notes in one module must merge, preserving rich text and deletions');
assert.equal(rebase(stickyBase, stickyBase, bundle({ stickyNotes: {} })).progress.stickyNotes.edited, undefined, 'an unchanged device must adopt a deleted note');
assert.equal(importGuest(bundle({ stickyNotes: { edited: sticky('Account') } }), bundle({ stickyNotes: { edited: sticky('Guest conflict'), guest: sticky('Guest note') } })).progress.stickyNotes.edited.content, 'Account');
assert.equal(importGuest(bundle(), bundle({ stickyNotes: { guest: sticky('<i>Guest note</i>') } })).progress.stickyNotes.guest.content, '<i>Guest note</i>');
assert.deepEqual(rebase(remote, remote, result), result, 'unchanged device must adopt the cloud snapshot');
assert.equal(rebase(base, local, bundle({ notes: { matrix: 'concurrent edit' } })).progress.notes.matrix, 'new explanation', 'local edit of the same note wins when saved last');

const run = { sessionId: 'test-1', end: 1000, questions: [1, 2], answers: { 0: 1 }, flags: [0], index: 0 };
const left = { ...run, answers: { 0: 1, 1: 2 }, flags: [], index: 1 };
const right = { ...run, answers: { 0: 3 }, flags: [0, 1] };
assert.deepEqual(rebase(bundle({}, run), bundle({}, left), bundle({}, right)).mock.answers, { 0: 3, 1: 2 });
assert.deepEqual(rebase(bundle({}, run), bundle({}, left), bundle({}, right)).mock.flags, [1]);
assert.equal(rebase(bundle({}, run), bundle({}, left), bundle()).mock, null, 'finished test must stay finished');
assert.equal(rebase(bundle({}, run), bundle({}, left), bundle({}, { ...right, sessionId: 'test-2' })).mock.sessionId, 'test-2', 'replaced test must not resurrect');
assert.equal(rebase(bundle({}, run), bundle({}, null), bundle({}, right)).mock, null, 'local submission removes active draft');
assert.equal(rebase(bundle({}, run), bundle({}, null), bundle({}, { ...right, sessionId: 'test-2' })).mock.sessionId, 'test-2', 'submitting an old test must not delete a replacement');
assert.equal(rebase(bundle(), bundle({}, run), bundle()).mock.sessionId, 'test-1', 'new draft must sync');
const duringWrite = bundle({ ...result.progress, notes: { ...result.progress.notes, matrix: 'typed during request' } });
assert.equal(rebase(result, duringWrite, result).progress.notes.matrix, 'typed during request', 'edits during a save must remain pending');

const imported = importGuest(bundle({ notes: { matrix: 'account note' }, completed: ['rank'], attempts: [{ eventId: 'same' }] }), bundle({ notes: { matrix: 'guest note', graph: 'guest graph' }, completed: ['rank', 'gaussian'], attempts: [{ eventId: 'same' }, { eventId: 'guest' }] }));
assert.equal(imported.progress.notes.matrix, 'account note');
assert.equal(imported.progress.notes.graph, 'guest graph');
assert.equal(imported.progress.attempts.length, 2);
assert.equal(importGuest(imported, bundle({ attempts: [{ eventId: 'guest' }] })).progress.attempts.length, 2, 'import must be idempotent');
const repeated = rebase(bundle(), bundle({ paperResults: [{ id: '2018', sessionId: 'one' }, { id: '2018', sessionId: 'two' }] }), bundle());
assert.equal(repeated.progress.paperResults.length, 2, 'separate attempts at the same paper are distinct');
console.log('Cloud merge checks passed: changes, removals, histories, active drafts, imports and in-flight edits.');
