import { PGlite } from '@electric-sql/pglite';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
const users=['11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','33333333-3333-4333-8333-333333333333'];
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth to anon,authenticated,service_role;grant execute on function auth.uid() to anon,authenticated,service_role;`);
for(const id of users)await db.query('insert into auth.users values($1)',[id]);
await db.exec(await readFile('supabase/migrations/202610040001_progress.sql','utf8'));
const sql=await readFile('supabase/migrations/202610080001_course_access.sql','utf8');
await db.exec(sql);await db.exec(sql);
async function identity(id,role=id?'authenticated':'anon'){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+role)}
const scalar=async(q,args=[])=>Object.values((await db.query(q,args)).rows[0])[0];
await db.exec(`insert into public.courses values('other-course','Other',true);
insert into public.course_lessons values('gate-cs-2027','preview',0,'{"id":"preview"}',true),('gate-cs-2027','paid',0,'{"id":"paid"}',false),('other-course','other',0,'{"id":"other"}',false);
insert into public.course_resources values('gate-cs-2027','questions','[]');`);
await identity(null);assert.equal(await scalar('select count(*)::int from public.course_lessons'),1);
assert.equal(await scalar('select count(*)::int from public.course_resources'),0);
assert.equal((await scalar("select public.course_access('gate-cs-2027')")).hasAccess,false);
await identity(users[0]);await db.query('select public.save_study_progress(0,$1::jsonb)',[JSON.stringify({progress:{notes:{secret:'private A'},role:'owner'}})]);
assert.equal(await scalar("select public.has_course_access('gate-cs-2027')"),false,'progress role cannot grant access');
for(const q of ["insert into account_roles values('"+users[0]+"','owner')","update account_roles set role='owner'","insert into course_entitlements(user_id,course_id,valid_from,valid_until) values('"+users[0]+"','gate-cs-2027',now(),now()+interval '1 year')","update payment_orders set status='paid'","select public.assign_course_owner('"+users[0]+"')"]){await assert.rejects(()=>db.exec(q),e=>e.code==='42501')}
const create=async(id,user=users[0],provider='order_'+id.replaceAll('-',''),amount=49900)=>{await identity(null,'service_role');await db.query('insert into payment_orders(id,user_id,course_id,amount,currency,provider_order_id) values($1,$2,$3,$4,$5,$6)',[id,user,'gate-cs-2027',amount,'INR',provider]);return provider};
const order=await create('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
const apply=async(event,orderId=order,pay='pay_ABC',kind='captured',amount=49900,currency='INR',hash='a'.repeat(64))=>scalar('select public.apply_course_payment($1,$2,$3,$4,$5,$6,$7)',[event,hash,orderId,pay,amount,currency,kind]);
await assert.rejects(()=>apply('wrongAmount',order,'pay_ABC','captured',1));
await assert.rejects(()=>apply('wrongCurrency',order,'pay_ABC','captured',49900,'USD'));
await assert.rejects(()=>apply('unknown','order_UNKNOWN'));
const granted=await apply('capture');assert.equal(granted.hasAccess,true);
const expiry=granted.validUntil;
assert.equal((await apply('capture')).duplicate,true);assert.equal((await apply('another_capture')).validUntil,expiry,'new event for same payment cannot extend pass');
await assert.rejects(()=>apply('capture',order,'pay_ABC','captured',49900,'INR','b'.repeat(64)));
await assert.rejects(()=>apply('wrongPayment',order,'pay_OTHER'));
await identity(users[0]);assert.equal(await scalar('select count(*)::int from course_lessons'),2);assert.equal(await scalar('select count(*)::int from course_resources'),1);
assert.equal(await scalar("select has_course_access('other-course')"),false);
await assert.rejects(()=>apply('untrustedCall'),e=>e.code==='42501');
await identity(users[1]);assert.equal(await scalar('select count(*)::int from course_lessons'),1);assert.equal(await scalar('select count(*)::int from payment_orders'),0);assert.equal(await scalar('select count(*)::int from course_entitlements'),0);
await identity(null,'service_role');await apply('refund',order,'pay_ABC','refunded');assert.equal((await apply('lateCapture')).hasAccess,false);
await identity(users[0]);assert.equal(await scalar("select has_course_access('gate-cs-2027')"),false);
const reversed=await create('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');await apply('earlyRefund',reversed,'pay_DEF','refunded');assert.equal((await apply('delayedCapture',reversed,'pay_DEF')).hasAccess,false);
const third=await create('cccccccc-cccc-4ccc-8ccc-cccccccccccc');await assert.rejects(()=>apply('reusedPayment',third,'pay_ABC'));
await apply('thirdCapture',third,'pay_XYZ');await db.query("update course_entitlements set valid_from=now()-interval '2 years',valid_until=now()-interval '1 day' where source_order=$1",['cccccccc-cccc-4ccc-8ccc-cccccccccccc']);
await identity(users[0]);assert.equal(await scalar("select has_course_access('gate-cs-2027')"),false,'expired pass denied');
const discounted=await create('dddddddd-dddd-4ddd-8ddd-dddddddddddd',users[1],'order_DISCOUNT',29900);
await assert.rejects(()=>apply('discountWrongAmount',discounted,'pay_SALE','captured',49900));
assert.equal((await apply('discountCapture',discounted,'pay_SALE','captured',29900)).hasAccess,true);
await identity(users[1]);assert.equal(await scalar('select count(*)::int from course_resources'),1,'Only confirmed discounted payment unlocks the bank');
await identity(null,'service_role');await scalar('select assign_course_owner($1)',[users[2]]);
await identity(users[2]);assert.equal(await scalar('select count(*)::int from course_lessons'),3);assert.equal(await scalar('select count(*)::int from study_progress'),0,'owner must not see another learner notes');
assert.equal((await scalar("select course_access('other-course')")).role,'owner');
await identity(null,'service_role');assert.equal(await scalar("select count(*)::int from access_audit where action='owner_assigned'"),1);
await db.exec("update courses set enabled=false where id='other-course'");await identity(users[2]);assert.equal(await scalar("select has_course_access('other-course')"),false);
await db.close();console.log('Course Postgres checks passed: previews, paid/expired/owner access, private notes, role escalation, trusted orders, payment IDs, duplicates and refund ordering.');
