const assert = require('node:assert/strict');
const T = require('../study-time.js');
const { rebase, importGuest } = require('../progress-merge.js');
const initial = Date.parse('2026-10-04T08:00:00Z');
const options = { sessionId: 'focus-one', mode: 'stopwatch', context: { kind: 'learning', lesson: '0-matrices-rank', subject: 0, label: 'Matrices' }, goal: 'Understand pivots' };
let timer = T.create(options, initial);
assert.equal(T.elapsed(timer, initial + 65000), 65000, 'elapsed time must not depend on tick frequency');
timer = T.pause(timer, initial + 65000);
assert.equal(T.elapsed(timer, initial + 125000), 65000, 'paused time must not count');
timer = T.resume(timer, initial + 125000);
assert.equal(T.elapsed(timer, initial + 130000), 70000);
const record = T.record(timer, initial + 130000);
assert.equal(record.durationMs, 70000);
assert.equal(record.segments.length, 2);
assert.equal(timer.status, 'running', 'saving a record must not mutate the active object');
assert.equal(T.elapsed(timer, initial), 65000, 'a backwards clock must not produce negative elapsed time');
assert.equal(T.record(T.create(options, initial), initial + 500), null, 'sub-second clicks are not study sessions');

let block = T.create({ ...options, mode: 'pomodoro', focusMinutes: 25, breakMinutes: 5 }, initial);
block = T.pause(block, initial + 10 * 60000);
block = T.resume(block, initial + 20 * 60000);
let result = T.advance(block, initial + 35 * 60000);
assert.equal(result.record.durationMs, 25 * 60000, 'focus block must cap exactly at its target after pauses');
assert.equal(result.timer.phase, 'break');
assert.equal(result.timer.runningSince, initial + 35 * 60000);
assert.equal(T.elapsed(result.timer, initial + 37 * 60000), 2 * 60000);
assert.deepEqual(T.activeSegments(result.timer, initial + 37 * 60000), [], 'breaks must never enter study totals');
result = T.advance(result.timer, initial + 90 * 60000);
assert.equal(result.timer.status, 'ready', 'late wake-up must finish the break without auto-starting another focus block');
assert.equal(result.record, null, 'break completion must not create another focus record');
const late = T.advance(T.create({ ...options, mode: 'pomodoro', focusMinutes: 25, breakMinutes: 5 }, initial), initial + 120 * 60000);
assert.equal(late.record.durationMs, 25 * 60000, 'browser sleep must not inflate Pomodoro focus time');
assert.equal(late.timer.status, 'ready');

const midnight = [{ start: Date.parse('2026-10-04T18:25:00Z'), end: Date.parse('2026-10-04T18:40:00Z') }];
assert.deepEqual(T.splitDays(midnight), { '2026-10-04': 5 * 60000, '2026-10-05': 10 * 60000 }, 'India midnight must allocate time to both dates');
assert.deepEqual(T.splitDays([{ start: 2, end: 1 }, { start: NaN, end: 5 }]), {});
assert.equal(T.totals([record, record], timer, initial + 140000)['2026-10-04'], 70000, 'saved and duplicate active records must not double count');
const overlap = { ...record, eventId: 'different-device', segments: [{ start: initial + 30000, end: initial + 75000 }] };
assert.equal(T.totals([record, overlap], null, initial + 140000)['2026-10-04'], 80000, 'overlapping timers on different devices must count each instant only once');
assert.equal(T.clock(3661000), '01:01:01');
assert.equal(T.duration(3661000), '1h 1m');
assert.equal(T.duration(32000), '32s');

const bundle = progress => ({ progress, mock: null, paperRun: null });
const merged = rebase(bundle({ focusSessions: [], focusReflections: {} }), bundle({ focusSessions: [record], focusReflections: { 'focus-one': { recall: 'Local recall' } } }), bundle({ focusSessions: [{ ...record, eventId: 'other-device' }], focusReflections: { 'other-device': { mistake: 'Remote mistake' } } }));
assert.equal(merged.progress.focusSessions.length, 2, 'finished sessions from separate devices must merge');
assert.equal(merged.progress.focusReflections['other-device'].mistake, 'Remote mistake');
assert.equal(merged.progress.focusReflections['focus-one'].recall, 'Local recall');
assert.equal(importGuest(bundle(merged.progress), bundle({ focusSessions: [record] })).progress.focusSessions.length, 2, 'guest import must not duplicate tracked time');
console.log('Study time checks passed: pause/resume, throttled ticks, exact Pomodoro limits, breaks, India midnight, deduplication and cloud merge.');
